### ISSUE TITLE
deploy seems to put state file in the wrong place

### ISSUE THREAD

**Issue by robdimsdale** [pivotal-cf-experimental/bosh-bootloader#11]
I ran the following command:
```
± |master S:3 ✗| → bbl \
--aws-access-key-id=$(cat ~/workspace/deployments-rmd/bbl-concourse/aws_access_key_id) \
--aws-secret-access-key=$(cat ~/workspace/deployments-rmd/bbl-concourse/aws_secret_access_key) \
--state-dir="~/workspace/deployments-rmd/bbl-concourse/state" \
--aws-region=us-east-1 \
unsupported-deploy-bosh-on-aws-for-concourse
```

and received the following error:
```

step: generating cloud config
step: applying cloud config


open ~/workspace/deployments-rmd/bbl-concourse/state/state.json: no such file or directory
```

Taking a look at what is on the filesystem, it seemed the `--state-dir` was not respected, and put the file in the wrong place, meaning it couldn't find it later:

```
 2016-04-08 19:44:41 ☆ ruby 2.1.8p440 rmd-macbook in ~/workspace/deployments-rmd
± |master S:3 ✗| → gst
On branch master
Your branch is up-to-date with 'origin/master'.
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	new file:   bbl-concourse/aws_access_key_id
	new file:   bbl-concourse/aws_secret_access_key
	new file:   state.json
```

Running the command without the `--state-dir` flag seemed to succeed.

**Comment by zankich** [comment]
@robdimsdale the problem is that you passed in a literal `~` in your path, and that directory doesn't exist. I've added a fast fail check https://github.com/pivotal-cf-experimental/bosh-bootloader/commit/e7c67dd3f8f9be5df6ea7ff1a26a844d18f5620d for a state-dir which doesn't exist.

Thanks for reporting the issue!

**Comment by robdimsdale** [comment]
Ah, right, because the `~` was inside quotes, so the shell doesn't expand it, and the literal `~` is passed to `bbl`.

Thanks for adding the fast-fail. I think that would have helped in my case.
