### ISSUE TITLE
concourse deployment should support ELB

### ISSUE THREAD

**Issue by robdimsdale** [pivotal-cf-experimental/bosh-bootloader#12]
Concourse web VMs should have an ELB in front of them, but currently there is no ELB information in the cloud config, meaning I have to download the cloud config, manually add ELB, and re-upload it, which means I'm working outside of the bbl tool, and I imagine that my config will be removed next time I run bbl (I haven't confirmed this though).

Also, we will need to configure cert information for the ELB somehow via bbl, otherwise we have to upload the certs out of band.

**Comment by Amit-PivotalLabs** [comment]
Already on roadmap:

* support LB in Cloud Config: https://www.pivotaltracker.com/story/show/115989445
* support specifying certs: https://www.pivotaltracker.com/story/show/115989461
