### ISSUE TITLE
User to use for ssh would be good to document

### ISSUE THREAD

**Issue by hhercules** [pivotal-cf-experimental/bosh-bootloader#17]
Since for on premises installs some users change to ubuntu I was unsure which user to use to login. I would be good to document that. New users and "seasoned" users like myself would find it helpful I think. 

For AWS users to use when I looked it up found this, but I realize any could be used:
https://alestic.com/2014/01/ec2-ssh-username/

This made reference to use ubuntu or root for Ubuntu, but did not think to use vcap although had used that previously.

**Comment by Amit-PivotalLabs** [comment]
Hey @hhercules 

Sorry for the delay.  `vcap` is the standard user for all BOSH installs, I've never seen anyone change this.  It's definitely good for users to know what user to SSH with, but I don't want this repository to be in the business of duplicating all the BOSH documentation.  Were you trying to SSH into the BOSH director itself, or some VM deployed with BOSH?

Amit

**Comment by hhercules** [comment]
I suppose I got this confused with ops manager and how it went from tempest to ubuntu. Thanks.
