### ISSUE TITLE
EBS Encryption

### ISSUE THREAD

**Issue by hhercules** [pivotal-cf-experimental/bosh-bootloader#20]
One requirement for using Public Cloud is encryption of at rest systems. So being able to enable encryption of EBS volumes would be required feature. Even better would be ability to use your own Encryption key.

**Comment by Amit-PivotalLabs** [comment]
Thanks @hhercules 

This may be as simple as setting `encrypted: true` in the disk pool for our bosh-init manifest, and changing the disk pool in the cloud config (or adding a new "encrypted" disk pool in addition to the existing "default" one) with the same setting.

Looks like EBS encryption also comes at no additional cost.

I investigated how BOSH handles toggling encryption in the disk pool, seems like it does the right thing (http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSEncryption.html#EBSEncryption_considerations) according to folks in the bosh Slack channel (https://cloudfoundry.slack.com/archives/bosh/p1463099453001976)

This setting is used in Pivotal's BOSH + CF offerings, and there have been no reported major performance impacts, so I think this is a safe change to make.  I will prioritize this for the team to work on.

Cheers,
Amit

**Comment by Amit-PivotalLabs** [comment]
To clarify, we will enable encryption (and you will not be able to opt out of it), but not providing a custom key.  As far as I can tell, this isn't even supported in BOSH.  It also adds some complexity to the UX, so if BOSH could support it, it may still not be appropriate for `bbl` which strives to be laser focused on simplicity and especially the new user persona.

**Comment by hhercules** [comment]
Very cool, thank you for investigating this.


Hercules, Christian Hildebrando
DevOps Cloud Services
Technology Solutions Group
CoreLogic

Direct 949-214-1471
Mobile 714-788-2309
hhercules@corelogic.com<mailto:hhercules@corelogic.com>

corelogic.com<http://www.corelogic.com/> |  Blog<http://www.corelogic.com/blog/default.aspx>
LinkedIn<http://www.linkedin.com/company/corelogic>  |  Twitter<http://twitter.com/corelogicinc> |  Facebook<http://www.facebook.com/CoreLogic>  |  Google+<https://plus.google.com/114618839782139347829>

Our Vision: Deliver unique property-level insights that power the global real estate economy

**Comment by Amit-PivotalLabs** [comment]
This feature, as described in my comments above, is now available.
