### ISSUE TITLE
bbl does not update internally stored bosh-init state when the bosh director gets updated

### ISSUE THREAD

**Issue by ryanmoran** [pivotal-cf-experimental/bosh-bootloader#21]
If there is a reason for `bosh-init` to update the director (ie. the version of the director CPI changes), `bosh-init` will redeploy a new VM with that update. This produces an updated `bosh-state.json` file as an output of running `bosh-init deploy`.

Upon inspection of the code [here](https://github.com/pivotal-cf-experimental/bosh-bootloader/blob/master/commands/up.go#L169), it looks like `bbl` will not update it's internal storage of this new state unless this state was previously empty.

In this case, the state is not empty, but was modified and should still be persisted. It seems like the fix would be to remove the above mentioned conditional so that the bosh state field always gets persisted.

**Comment by zankich** [comment]
@ryanmoran should be fixed in https://github.com/pivotal-cf-experimental/bosh-bootloader/commit/159dc5f3fca99ecd79e1265d538efc8cc96013a4, thanks!
