### ISSUE TITLE
Rollback not deleting key pairs

### ISSUE THREAD

**Issue by albertoleal** [pivotal-cf-experimental/bosh-bootloader#26]
We got some failures while trying to spin up a new environment and saw that the key pairs weren't deleted as part of the cloud formation roll back.

**Comment by Amit-PivotalLabs** [comment]
Thanks for raising this issue @albertoleal.  This will be solved when we undertake the track to make `bbl` re-entrant, which will happen before we officially release it.  You can see this Pivotal Tracker *epic* here: https://www.pivotaltracker.com/epic/show/2401727

Thanks,
Amit
