### ISSUE TITLE
Customizable vm_types in cloud config

### ISSUE THREAD

**Issue by robdimsdale** [pivotal-cf-experimental/bosh-bootloader#29]
Similar to #28 but for `vm_types`; we need a way to be able to specific my how ephemeral disk a `vm_type` has - currently they all have 1 GB. Our concourse workers typically need about 100GB, and currently we have to edit the generated `cloud_config` and operate outside of bbl's visibility. We'd like a way to be able to choose the `vm_types` properties in such a way that `bbl` knows about them.

**Comment by Amit-PivotalLabs** [comment]
We should add the following `vm_extensions`:

* `5GB_ephemeral`: `{cloud_properties: {ephemeral_disk: size: 5120}}`
* `10GB_ephemeral`: `{cloud_properties: {ephemeral_disk: size: 10240}}`
* `50GB_ephemeral`: `{cloud_properties: {ephemeral_disk: size: 51200}}`
* `100GB_ephemeral`: `{cloud_properties: {ephemeral_disk: size: 102400}}`
* `500GB_ephemeral`: `{cloud_properties: {ephemeral_disk: size: 512000}}`
* `1TB_ephemeral`: `{cloud_properties: {ephemeral_disk: size: 1048576}}`

**Comment by robdimsdale** [comment]
Sounds good. How will this impact the existing `cloud_properties.ephemeral_disk`? Does `vm_extensions` override this value?

**Comment by Amit-PivotalLabs** [comment]
This features is now available.
