### ISSUE TITLE
unsupported-create-lbs is not idempotent

### ISSUE THREAD

**Issue by DennisDenuto** [pivotal-cf-experimental/bosh-bootloader#31]
It would be useful if unsupported-create-lbs did not fail if a lb has been previously created. (unsupported-deploy-bosh-on-aws-for-concourse performs a no-op. This functionality would be ideal for unsupported-create-lbs)

**Comment by Amit-PivotalLabs** [comment]
@DennisDenuto there is a `--skip-if-exists` flag you can use.  It was implemented very recently, but was rejected.  You can track the progress of this story here: https://www.pivotaltracker.com/story/show/119213225
