### ISSUE TITLE
bbl should have command to display load balancer information

### ISSUE THREAD

**Issue by robdimsdale** [pivotal-cf-experimental/bosh-bootloader#35]
When we use `bbl` to create a load balancer, we need to setup DNS out of band to route to it. If bbl could provide some information about the LB, perhaps it only needs to be the host DNS address, it would greatly simplify automating of the out-of-band DNS configuration

**Comment by Amit-PivotalLabs** [comment]
Thanks.  You're right, this should be in the README and the `bbl` usage output.

**Comment by christianang** [comment]
There is now a `bbl lbs` command that you can use to display the load balancer information. It is also now documented in the README and usage.

Thanks.
-Christian and @kkallday

**Comment by robdimsdale** [comment]
Thanks, I see it. I haven't used it, but I'll close this issue and open a new one if I run into any issues.
