### ISSUE TITLE
bbl should optionally provide output in machine-parseable format

### ISSUE THREAD

**Issue by robdimsdale** [pivotal-cf-experimental/bosh-bootloader#36]
The human-readable output of commands like `unsupported-lbs` is good for humans, but brittle when it comes to machine parsing.

If `bbl` supported a `--output-format=[human|json|yaml]` flag, it would greatly improve the experience of scripting it.

**Comment by robdimsdale** [comment]
Putting on my engineering hat and thinking about implementation, I've done this in the [PivNet CLI](https://github.com/pivotal-cf-experimental/go-pivnet) - it wasn't that challenging; it just requires models for the presentation layer.

**Comment by ryanmoran** [comment]
I also just ran into this and wished for something better here. Writing a bash chainsaw like, `bbl --state-dir ~/.bbl | grep "Concourse LB:" | awk '{print $4}' | tr -d "[]"` made me feel 😿 .

**Comment by Amit-PivotalLabs** [comment]
Thanks @robdimsdale @ryanmoran 

Currently `lbs` is the only command I can think of that is a read operation and doesn't provide output in a scriptable format, e.g. the output of `director-address` is fine.  So we can scope this conversation to `lbs`.  Now, looking at its output, it gives you something like this:

```
CF Router LB: SomeAWSResourceName [aws-elb-blah.aws.amazon.ec2.com]
CF SSH Proxy LB: AnotherAWSResourceName [foo.bar.ec2.elb.amazon]
```

**Is the AWS resource name even useful?**  I wonder if the logical name and the URL would be sufficient.  Something like:

```
CF Router LB: aws-elb-blah.aws.amazon.ec2.com
CF SSH Proxy LB: foo.bar.ec2.elb.amazon
```

Then you'd get:

```
$ bbl lbs | grep "Router" | cut -f2 -d: | tr -d ' '
```

vs

```
$ bbl lbs --output-format=json | jq -r '."CF Router LB"'
```

At that point, I'm not sure I see a massive amount of value in the output format flag.  I could see it being something for future consideration.

**Comment by zankich** [comment]
I was talking with @ryanmoran and he suggested that `lbs` could optionally accept the lb type and only return that value. So it would be something like
```
$ bbl lbs --type CFRouter
router.elb.com
```

And then the `lbs` command with no argument would exhibit it's current behavior.

**Comment by ryanmoran** [comment]
@Amit-PivotalLabs the resource name is useful when you want to setup an A record with an alias target.

**Comment by ryanmoran** [comment]
@Amit-PivotalLabs in order to get an alias target we would also need the hosted zone id of the ELB.

**Comment by ryanmoran** [comment]
@Amit-PivotalLabs the reason this matters is that sometimes you might need an A record, and without something like an alias target, you can only setup a CNAME record.

**Comment by Amit-PivotalLabs** [comment]
@ryanmoran when do you want an A record instead of a CNAME?

**Comment by ryanmoran** [comment]
@Amit-PivotalLabs you can't create a CNAME that points to the top-level domain. So, you wouldn't be able to have a CNAME for pivotal.io. You would need an A Record. But you can make a CNAME for pretty much anything else. I don't have this problem, but its worth knowing that you can run into it.

**Comment by ryanmoran** [comment]
@Amit-PivotalLabs we actually ran into this CNAME vs A record issue today. If I have a hosted zone called `banana.fruit.example.com` and I have setup a hosted zone for `banana.fruit.example.com` which handles the redirected DNS lookup from some other NS, like `fruit.example.com`. I can't use a CNAME to set the apex record for the `banana.fruit.example.com` record. Instead, I need to specify an A record with an alias target that point at the ELB. And even more, I need to know the HostedZoneID that the ELB is in.

So, I propose that `bbl` include the ELBs HostedZoneID in addition to the other fields that it already includes.

**Comment by Amit-PivotalLabs** [comment]
@ryanmoran @robdimsdale @zankich How about:

```
$ bbl lbs
CF Router LB:
  Domain Name: some.elb.com
  AWS Resource Name: SomeAWSResourceName
  AWS Hosted Zone ID: XYZ
CF SSH Proxy LB:
  Domain Name: another.elb.com
  AWS Resource Name: AnotherAWSResourceName
  AWS Hosted Zone ID: ABC

$ bbl lbs --json
{
  "CF Router LB": {
    "Domain Name": "some.elb.com",
    "AWS Resource Name": "SomeAWSResourceName",
    "AWS Hosted Zone ID": "XYZ"
  }, 
  "CF SSH Proxy LB": {
    "Domain Name": "another.elb.com",
    "AWS Resource Name": "AnotherAWSResourceName",
    "AWS Hosted Zone ID": "ABC"
  }
}
```

Of course, this is very AWS-specific, but we can figure out something similar when we get to our next IaaS.

One question @ryanmoran what is HostedZoneID, and is it different from what I'm calling AWSResourceName?

**Comment by ryanmoran** [comment]
@Amit-PivotalLabs HostedZoneID is a property of the ELB. If you look at the load balancer description page in the EC2 dashboard, you will see something like `Z123ABC`. We will need that value to setup an A record with an alias target.

**Comment by robdimsdale** [comment]
I think that the proposed solution above would meet all of the needs I have discovered so far, thanks

**Comment by Amit-PivotalLabs** [comment]
Story created: https://www.pivotaltracker.com/story/show/126362385

**Comment by zankich** [comment]
necro bump

**Comment by evanfarrar** [comment]
Why do you get the IP of the CF TCP Router LB? i.e. What do you do with it after you get it?
