### ISSUE TITLE
unavailable availability zone

### ISSUE THREAD

**Issue by jtarchie** [pivotal-cf-experimental/bosh-bootloader#45]
`bbl` assumes that the account being used has access to specific availability zones -- `us-east-1b`. My account is actually not able to produce things on that AZ.

The Cloud Formation template errors:

> Value (us-east-1b) for parameter availabilityZone is invalid. Subnets can currently only be created in the following availability zones: us-east-1a, us-east-1c, us-east-1d, us-east-1e.

This happened while trying to create the subnets across AZs.

**Comment by Amit-PivotalLabs** [comment]
Hey @jtarchie 

What command were you running?  Can you see CloudFormation events in the AWS console that say which subnet it was creating when it failed?

**Comment by jtarchie** [comment]
1. Ran the `bbl` create command.
2. The events show `InternalSubnet2` could not be created.

**Comment by Amit-PivotalLabs** [comment]
@jtarchie `bbl` isn't assuming anything about `us-east-1b`.  It's using the [intrinsic CloudFormation function `Fn::GetAZs`](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-getavailabilityzones.html) which is supposed to do the right thing based on the linked doc.  It produces a template that looks like [this](https://github.com/pivotal-cf-experimental/bosh-bootloader/blob/master/aws/cloudformation/templates/fixtures/cloudformation_without_elb.json#L312-L322):

```
        "InternalSubnet2": {
            "Properties": {
                "AvailabilityZone": {
                    "Fn::Select": ["1", {"Fn::GetAZs": {"Ref": "AWS::Region"}}]
                },
                "CidrBlock": {"Ref": "InternalSubnet2CIDR"},
                "Tags": [{"Key": "Name", "Value": "Internal2"}],
                "VpcId": {"Ref": "VPC"}
            },
            "Type": "AWS::EC2::Subnet"
        },
```

To clarify, do you have no access to `us-east-1b` in your account at all, or do you simply not have access to it for VPC/subnet purposes?

**Comment by jtarchie** [comment]
Based on other VPCs I created in `us-east-1`, it would appear I don't have access to `us-east-1b` at all.

**Comment by Amit-PivotalLabs** [comment]
@jtarchie are you using a very old account, possible one that predated the existence of VPCs?

* http://stackoverflow.com/questions/22744467/vpc-capable-availability-zones-in-amazon/22812138#22812138
* http://stackoverflow.com/questions/21390444/is-there-a-way-for-cloudformation-to-query-available-zones-for-subnet-creation
* https://github.com/deis/deis/issues/1601

**Comment by jtarchie** [comment]
It would appear to be that. I've created a new account.

**Comment by Amit-PivotalLabs** [comment]
Cool, hope that wasn't a huge inconvenience.

**Comment by jchester** [comment]
Is there some unambiguous way to tell if I'm in the pre/post VPC-is-OK world?

**Comment by jchester** [comment]
Never mind, found an access key from 2009. Sooooooo I'm gunna guess it predates the VPC-is-OK world.
