### ISSUE TITLE
Argument parsing order

### ISSUE THREAD

**Issue by supertopher** [pivotal-cf-experimental/bosh-bootloader#48]
Upon initial use, i attempted to run the command 

```bbl unsupported-deploy-bosh-on-aws-for-concourse --aws-access-key-id="KEY"```

when bbl wanted 

```bbl --aws-access-key-id="KEY"  unsupported-deploy-bosh-on-aws-for-concourse```

feel free to blame user error here, but given that amit emailed me the commands in the incorrect order as well i think it seems intuitive to put the commands in an order bbl doesn't recognise

**Comment by Amit-PivotalLabs** [comment]
Current usage says `bbl [GLOBAL OPTIONS] COMMAND [OPTIONS]`.  We have a placeholder story to make all the flags make sense (https://www.pivotaltracker.com/story/show/117015689).  One of thing things we'll do is make `--state-dir` a global option, but move the AWS-specific stuff a command-specific option on the `up` command (currently known as `unsupported-deploy-...`).  Would that UX make more sense to you?

**Comment by Amit-PivotalLabs** [comment]
So

```
$ bbl [--state-dir=XXX] up [--aws-region=XXX] [--aws-sec...] [--aws-acc...]
```

**Comment by Amit-PivotalLabs** [comment]
@supertopher going to assume the stuff I said above makes sense to you. Closing.
