### ISSUE TITLE
Compilation VM number is too small for timely CF deployment

### ISSUE THREAD

**Issue by supertopher** [pivotal-cf-experimental/bosh-bootloader#50]
At cloud ops we favor a pretty robust compilation VM size and number.  If you do a deployment during the work day, programmer time costs alot more than VM time.  

`3` VM takes a long time to deploy CF.  We set our cloud config to a more liberal `6`.

**Comment by Amit-PivotalLabs** [comment]
Agreed, 6 would be nicer.  Prioritizing.

**Comment by jchester** [comment]
The flipside is that this happens to people who set up brand-new accounts to fix #45:

> Error 100: Unknown CPI error 'Unknown' with message 'You have requested more instances (6) than your current instance limit of 5 allows for the specified instance type. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.'
