### ISSUE TITLE
Document AWS policy

### ISSUE THREAD

**Issue by robdimsdale** [pivotal-cf-experimental/bosh-bootloader#9]
I created a new AWS user and gave it `Administrator Access` policy. When I use the corresponding secret access id and key I get the following error:

```
± |master ?:2 ✗| → bbl --aws-access-key-id=$(cat ~/workspace/deployments-rmd/bbl-concourse/aws_access_key_id) --aws-secret-access-key=$(cat ~/workspace/deployments-rmd/bbl-concourse/aws_secret_access_key) --state-dir="~/workspace/deployments-rmd/bbl-concourse/state" --aws-region=us-east-1 unsupported-deploy-bosh-on-aws-for-concourse
step: creating keypair


UnauthorizedOperation: You are not authorized to perform this operation.
	status code: 403, request id:
```

Can we document what permissions are expected of the user associated with the keypair?

**Comment by robdimsdale** [comment]
Well, turns out I had to wait a couple of minutes for the policy to take effect, so it looks like `Administrator Access` is good, but we should document that it might take a few minutes to take effect

**Comment by Amit-PivotalLabs** [comment]
This info has been added to README. Closing.
